### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by memetc** [bounswe/bounswe2020group1#136]
Test your API using a tool like Postman, HTTP Get, or similar tools

**Comment by AsenaKarolin** [comment]
Test cases for the search functionality are created. You can view them at:
https://github.com/bounswe/bounswe2020group1/blob/master/Test%20Cases/search_test_cases.py

**Comment by yagizcolak** [comment]
Test cases for the comment functionality are created. It can be viewed at:
https://github.com/bounswe/bounswe2020group1/blob/master/Test%20Cases/test_comment.py

**Comment by memetc** [comment]
I added the test cases for creating a new product.  Test results indicate that according HTML file should be revised in order to change the fields to 'required'. Right now a product with an empty name or empty seller field can be created. The test cases can be viewed here : https://github.com/bounswe/bounswe2020group1/tree/master/Test%20Cases

**Comment by memetc** [comment]
Necessary tests are implemented.
