### ISSUE TITLE
User Scenarios and Mockups Review

### ISSUE THREAD

**Issue by AsenaKarolin** [bounswe/bounswe2020group1#139]
Making necessary changes to the user scenarios and mockups.

**Comment by AsenaKarolin** [comment]
I have updated the scenarios, mockups and acceptance criteria of the scenario 1 & 2.Changes can be observed at https://github.com/bounswe/bounswe2020group1/wiki/User-Scenarios-and-Mock-ups

**Comment by alibatir** [comment]
I have updated the scenarios, mockups and acceptance criteria of the scenario 3.
