### ISSUE TITLE
Class Diagram Review

### ISSUE THREAD

**Issue by sezgineray** [bounswe/bounswe2020group1#141]
Review and make necessary updates to the project's class diagram.

**Comment by onurkilic2301** [comment]
- Read the "Sign-in with Google" documentation and updated the functionality in the class diagram
- Added ProductList class, and changed the Customer class accordingly 
- Updated the Product class and deleted the Tag class

**Comment by memetc** [comment]
- FilterEngine revisited and updated. Filter, sort, search methods are simplified.
- In RecommendationEngine,  getRecommendations method is edited, clientIPAdress is added as a parameter in order to access server activity.
