### ISSUE TITLE
Merge backend, frontend and android to master.

### ISSUE THREAD

**Issue by barisalhan** [bounswe/bounswe2020group1#202]

**Comment by onurkilic2301** [comment]
Merged backend to the master.

**Comment by barisalhan** [comment]
Done with following PRs.
[PR-1](https://github.com/bounswe/bounswe2020group1/pull/205)
[PR-2](https://github.com/bounswe/bounswe2020group1/pull/204)
[PR-3](https://github.com/bounswe/bounswe2020group1/pull/201)
