### ISSUE TITLE
Complete and submit the Customer Milestone 1 Report

### ISSUE THREAD

**Issue by lighterm** [bounswe/bounswe2020group1#210]
For customer milestone 1, all the assignees need to complete their assigned parts and merge the documents to a single pdf file. Then communicator needs to submit the document before 29/11/2020 23.59.

**Comment by barisalhan** [comment]
Done. Here is the [link](https://github.com/bounswe/bounswe2020group1/wiki/CMPE451---Milestone-%231---(24.11.2020)) of the wiki page.
