### ISSUE TITLE
Vote for the suggested group names

### ISSUE THREAD

**Issue by onurkilic2301** [bounswe/bounswe2020group1#23]
- [x] Ömer
- [ ] Barış Alhan
- [x] Ali 
- [ ] Yağız
- [x] Murat 
- [ ] Buse 
- [ ] Ufuk 
- [ ] Onur
- [ ] Barış Mutlu
- [x] Asena 
- [ ] Mehmet

**Comment by memetc** [comment]
I suggets the names lydia or sardis as they are ancient and important names in the history of commerce. Moreover heritage of anatolian history would be emphasized.
