### ISSUE TITLE
About issues without description

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group1#24]
Dear all,

Please note that each issue should contain **at least one assignee and label**. Besides these, it should also contain **an explanatory title** as well as **a proper description**. Moreover, even though it is not always possible, try to specify the **priority level** and the **deadline** while writing the issues. Last but not least, try to **distribute the issues equally** among team members both in terms of assignee and owner of the issue (i.e., rather than a few people, every single team member should open a sufficient amount of open issues).

Best,
Meriç

**Comment by mericturan** [comment]
I cannot assign more than 10 people to an issue. That is why I could not assign this issue to @utulb.

**Comment by AsenaKarolin** [comment]
Thank you for your feedback. We will keep your warnings and suggestions in mind.
