### ISSUE TITLE
Create Messaging Interface

### ISSUE THREAD

**Issue by AsenaKarolin** [bounswe/bounswe2020group1#354]
Create a messaging interface where users can start new chats and send messages in the web.

**Comment by AsenaKarolin** [comment]
A draft for the messaging interface is created.
However the following points need attention:
- [x]  The already contacted vendors should not appear as an option for a new chat.
- [ ]  The sidebar and the messages should be scrowlable components.
- [ ]  The most recently contacted vendor should appear on the top.

**Comment by AsenaKarolin** [comment]
Further points:
- [x]  For vendors the message flow with the admin should be created with respect to a product or an order.
- [x]  Newly created message flows shall be updated on the sidebar.

**Comment by memetc** [comment]
**What is implemented so far:**
- Search page layout is implemented.
- Connection between customer profiles and vendor profile is established.
- Sendin message from vendor to admin is established.

**What remains:**
- Receiving message and sending message in admin profile still remains.

**Comment by memetc** [comment]
- [x] Receiving messages and sending messages in admin profile accomplished.
- [x]  Message bubbles are created.
