### ISSUE TITLE
Revising requirements and defining it in more detail 

### ISSUE THREAD

**Issue by busekabakoglu** [bounswe/bounswe2020group1#37]
Eveyone will review their written requirements and define it in more detail.

**Comment by memetc** [comment]
- [x]  Asena
 - [x]  Barış A.
 - [x]  Barış M.
 - [x]  Buse
 - [x]  Ali
 - [x]  Onur
 - [x]  Yağız
 - [x]  Murat
 - [x]  Mehmet
 - [x]  Ömer
 - [x]  Ufuk
