### ISSUE TITLE
Backend/Bug - Notification system return price change notification instead of stock change notification.

### ISSUE THREAD

**Issue by barisalhan** [bounswe/bounswe2020group1#404]
System should return type 5 notification when stock level is above a certain level. But it returns type 4 notification instead.

**Comment by lighterm** [comment]
Were you able to double check it? I think there might be a misunderstanding due to the indexing. I changed the alert indexing, now it will start from 1.

**Comment by lighterm** [comment]
Changed the indexing of alert types. It now starts from 1. This solves the issue.
