### ISSUE TITLE
Create Use Case Diagram

### ISSUE THREAD

**Issue by alibatir** [bounswe/bounswe2020group1#58]
Use Case Diagram will be prepared.
Deadline: Monday 23:59

**Comment by AsenaKarolin** [comment]
I created the use case diagram for the customer. You can view it at https://github.com/bounswe/bounswe2020group1/wiki/Use-Case-Diagrams

**Comment by yagizcolak** [comment]
I created the use case diagram for the vendor. You can view it at https://github.com/bounswe/bounswe2020group1/wiki/Use-Case-Diagrams

**Comment by utulb** [comment]
I created the use case diagram for the guest. You can view it at
[https://github.com/bounswe/bounswe2020group1/wiki/Use-Case-Diagrams](url)
